# Generated by Django 5.2.3 on 2025-07-02 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('graduate', 'Graduate'), ('not graduate', 'Not Graduate')], default='graduate', max_length=12)),
                ('emplyement_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], default='employed', max_length=10)),
                ('dependents', models.ImageField(default=0, upload_to='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
