# Generated by Django 5.2.3 on 2025-07-02 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='commercial_asset',
            field=models.IntegerField(default=300000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19400000)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='credit_score',
            field=models.IntegerField(default=350, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='income',
            field=models.IntegerField(default=200000, validators=[django.core.validators.MinValueValidator(200000), django.core.validators.MaxValueValidator(9900000)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='loan_amount',
            field=models.IntegerField(default=300000, validators=[django.core.validators.MinValueValidator(300000), django.core.validators.MaxValueValidator(39500000)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='loan_term',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='luxury_asset',
            field=models.IntegerField(default=300000, validators=[django.core.validators.MinValueValidator(300000), django.core.validators.MaxValueValidator(39200000)]),
        ),
        migrations.AddField(
            model_name='approvalmodel',
            name='resident_asset',
            field=models.IntegerField(default=300000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(29100000)]),
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='dependents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
