# Generated by Django 5.2.3 on 2025-07-03 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_approvalmodel_commercial_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='bank_asset',
            field=models.IntegerField(default=300000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14700000)]),
        ),
    ]
